apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: example-vpa
  namespace: default
  annotations:
    vpa-rollout.influxdata.io/enabled: "true"
    vpa-rollout.influxdata.io/diff-percent-trigger: "15"
    vpa-rollout.influxdata.io/cooldown-period: "2m"
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: vote
      controlledResources:
      - cpu
      - memory
      maxAllowed:
        cpu: "2"
        memory: 2Gi
      minAllowed:
        cpu: 500m
        memory: 200Mi
    - containerName: '*'
      mode: "Off"
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydeployment
  updatePolicy:
    updateMode: Initial
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote
        ports:
        - containerPort: 80
          name: vote
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            memory: 1Gi